const LOOKUP_URL='https://n8n.estyl.team/webhook/mol-terminy-aplikacja-magazynowa';
const ANALYZE_URL='https://n8n.estyl.team/webhook/mol-batch-reader';
const IMAGE_MAX_SIDE=1600;
const IMAGE_JPEG_QUALITY=0.80;
const IMAGE_SKIP_BYTES=900*1024;
const $=id=>document.getElementById(id);
const els={offline:$('offline'),connectionBadge:$('connectionBadge'),processing:$('processing'),processingTitle:$('processingTitle'),processingMsg:$('processingMsg'),processingTime:$('processingTime'),screenEan:$('screenEan'),screenPhoto:$('screenPhoto'),screenResult:$('screenResult'),step1:$('step1'),step2:$('step2'),step3:$('step3'),eanInput:$('eanInput'),eanStatus:$('eanStatus'),productCard:$('productCard'),productName:$('productName'),productBrand:$('productBrand'),productSku:$('productSku'),photoInput:$('photoInput'),photoStatus:$('photoStatus'),backBtn:$('backBtn'),resultMark:$('resultMark'),resultTitle:$('resultTitle'),resultLead:$('resultLead'),expiryValue:$('expiryValue'),batchValue:$('batchValue'),productionValue:$('productionValue'),sourceValue:$('sourceValue'),sourceDetail:$('sourceDetail'),resultProduct:$('resultProduct'),confidenceValue:$('confidenceValue'),nextBtn:$('nextBtn'),retryBtn:$('retryBtn')};
const state={product:null,result:null,busy:false,timer:null,started:0};
function text(v,f='—'){const s=String(v??'').trim();return s||f;}
function show(e){e?.classList.remove('hidden')}
function hide(e){e?.classList.add('hidden')}
function setStatus(e,type,msg){e.className='status '+type;e.textContent=msg;}
function clearStatus(e){e.className='status hidden';e.textContent='';}
function go(step){[els.screenEan,els.screenPhoto,els.screenResult].forEach((x,i)=>x.classList.toggle('active',i===step-1));[els.step1,els.step2,els.step3].forEach((x,i)=>{x.classList.toggle('active',i===step-1);x.classList.toggle('done',i<step-1);});window.scrollTo(0,0);if(step===1)setTimeout(()=>els.eanInput.focus(),100);}
function startProcessing(title,msg){state.busy=true;els.processingTitle.textContent=title;els.processingMsg.textContent=msg;els.processingTime.textContent='0 s';show(els.processing);state.started=Date.now();clearInterval(state.timer);state.timer=setInterval(()=>els.processingTime.textContent=Math.floor((Date.now()-state.started)/1000)+' s',1000);}
function stopProcessing(){state.busy=false;clearInterval(state.timer);state.timer=null;hide(els.processing);}
function sizeLabel(bytes){if(bytes<1024)return bytes+' B';if(bytes<1024*1024)return Math.round(bytes/1024)+' KB';return (bytes/(1024*1024)).toFixed(1)+' MB';}
async function decodeImage(file){if('createImageBitmap' in window){try{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});return{source:bitmap,width:bitmap.width,height:bitmap.height,cleanup:()=>bitmap.close?.()};}catch(_){try{const bitmap=await createImageBitmap(file);return{source:bitmap,width:bitmap.width,height:bitmap.height,cleanup:()=>bitmap.close?.()};}catch(__){}}}const url=URL.createObjectURL(file);const img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('IMAGE_DECODE_FAILED'));img.src=url;});return{source:img,width:img.naturalWidth||img.width,height:img.naturalHeight||img.height,cleanup:()=>URL.revokeObjectURL(url)};}catch(e){URL.revokeObjectURL(url);throw e;}}
async function optimizeImage(file){if(!file||!String(file.type||'').startsWith('image/'))return{file,optimized:false,originalSize:file?.size||0,finalSize:file?.size||0};let decoded;try{decoded=await decodeImage(file);const maxSide=Math.max(decoded.width,decoded.height);if(file.type==='image/jpeg'&&maxSide<=IMAGE_MAX_SIDE&&file.size<=IMAGE_SKIP_BYTES)return{file,optimized:false,originalSize:file.size,finalSize:file.size};const scale=Math.min(1,IMAGE_MAX_SIDE/maxSide);const width=Math.max(1,Math.round(decoded.width*scale));const height=Math.max(1,Math.round(decoded.height*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('CANVAS_UNAVAILABLE');ctx.drawImage(decoded.source,0,0,width,height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',IMAGE_JPEG_QUALITY));canvas.width=1;canvas.height=1;if(!blob)throw new Error('IMAGE_COMPRESS_FAILED');if(blob.size>=file.size&&maxSide<=IMAGE_MAX_SIDE)return{file,optimized:false,originalSize:file.size,finalSize:file.size};const compressed=new File([blob],'batch.jpg',{type:'image/jpeg',lastModified:Date.now()});return{file:compressed,optimized:true,originalSize:file.size,finalSize:compressed.size};}catch(_){return{file,optimized:false,originalSize:file.size,finalSize:file.size};}finally{decoded?.cleanup?.();}}
async function lookupProduct(ean){const fd=new FormData();fd.append('action','lookup_ean');fd.append('ean',ean);const r=await fetch(LOOKUP_URL,{method:'POST',body:fd,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||('HTTP_'+r.status));return d;}
async function analyze(ean,file){els.processingMsg.textContent='Optymalizuję zdjęcie przed wysłaniem…';const prepared=await optimizeImage(file);els.processingMsg.textContent=prepared.optimized?'Wysyłam zdjęcie '+sizeLabel(prepared.finalSize)+' zamiast '+sizeLabel(prepared.originalSize)+'…':'Wysyłam zdjęcie do rozpoznania…';const fd=new FormData();fd.append('action','recognize_batch');fd.append('ean',ean);fd.append('data',prepared.file,prepared.file.name||'batch.jpg');const r=await fetch(ANALYZE_URL,{method:'POST',body:fd,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||('HTTP_'+r.status));return d;}
function reset(){state.product=null;state.result=null;els.eanInput.value='';els.photoInput.value='';clearStatus(els.eanStatus);clearStatus(els.photoStatus);hide(els.productCard);els.productName.textContent='—';els.productBrand.textContent='—';els.productSku.textContent='—';go(1);}
async function onEan(){if(state.busy)return;const ean=els.eanInput.value.trim().replace(/\s+/g,'');if(!ean)return;clearStatus(els.eanStatus);hide(els.productCard);startProcessing('Sprawdzam produkt','Weryfikuję EAN w bazie MOL…');try{const d=await lookupProduct(ean);stopProcessing();if(!d.found){setStatus(els.eanStatus,'err','EAN nie został znaleziony. Zeskanuj ponownie.');els.eanInput.select();return;}state.product=d;els.productName.textContent=text(d.Nazwa);els.productBrand.textContent=text(d.Producent);els.productSku.textContent=text(d.SKU);show(els.productCard);setStatus(els.eanStatus,'ok','Produkt rozpoznany.');setTimeout(()=>{go(2);setTimeout(()=>els.photoInput.click(),180);},450);}catch(e){stopProcessing();setStatus(els.eanStatus,'err','Błąd sprawdzania EAN: '+e.message);}}
function prettySource(d){const raw=String(d.source||d.sourceDekodowania||'').trim();const map=[['CHECKCOSMETIC','CheckCosmetic'],['COSMETICCHECK','CosmeticCheck'],['CHECKFRESH','CheckFresh'],['DOLCE','Dolce'],['LOCAL_RULE','Reguła lokalna MOL'],['REGUŁA LOKALNA MOL','Reguła lokalna MOL'],['CACHE','Pamięć dekodera MOL'],['PAMIĘĆ DEKODERA','Pamięć dekodera MOL'],['GEMINI VISION','Odczyt ze zdjęcia · Gemini Vision'],['OPAKOWANIE','Odczyt ze zdjęcia · Gemini Vision']];const upper=raw.toUpperCase();for(const [k,v] of map){if(upper.includes(k))return v;}return raw||'Nieustalone';}
function confidenceLabel(v){const x=String(v||'').toLowerCase();return x==='high'?'wysoka':x==='medium'?'średnia':x==='low'?'niska':text(v);}
function renderResult(d){state.result=d;const success=Boolean(d.expiryDate||d.productionDate||d.batch);els.resultMark.textContent=success?'✓':'!';els.resultMark.classList.toggle('fail',!success);els.resultTitle.textContent=d.expiryDate?'Termin rozpoznany':d.batch?'Partia odczytana':'Brak pewnego wyniku';els.resultLead.textContent=d.expiryDate?'Rozpoznano partię i ustalono datę. Wynik nie jest zapisywany.':'Kod partii został odczytany, ale nie udało się wiarygodnie ustalić daty. Wynik nie jest zapisywany.';els.expiryValue.textContent=text(d.expiryDate);els.batchValue.textContent=text(d.batch);els.productionValue.textContent=text(d.productionDate);els.sourceValue.textContent=prettySource(d);els.sourceDetail.textContent=text(d.sourceDetail||d.sourceUrl||d.status||d.statusDekodowania);els.resultProduct.textContent=text(d.Nazwa||state.product?.Nazwa);els.confidenceValue.textContent=confidenceLabel(d.confidence);go(3);}
async function onPhoto(){if(state.busy||!state.product)return;const file=els.photoInput.files?.[0];if(!file)return;clearStatus(els.photoStatus);startProcessing('Rozpoznaję partię','Przygotowuję zdjęcie…');try{const d=await analyze(state.product.EAN,file);stopProcessing();if(!d.success){setStatus(els.photoStatus,'err',d.message||d.error||'Nie udało się przeanalizować zdjęcia.');return;}renderResult(d);}catch(e){stopProcessing();setStatus(els.photoStatus,'err','Błąd analizy: '+e.message);}}
els.eanInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();onEan();}});
els.photoInput.addEventListener('change',onPhoto);
els.backBtn.addEventListener('click',reset);
els.nextBtn.addEventListener('click',reset);
els.retryBtn.addEventListener('click',()=>{els.photoInput.value='';clearStatus(els.photoStatus);go(2);setTimeout(()=>els.photoInput.click(),120);});
function online(){const on=navigator.onLine;els.offline.classList.toggle('show',!on);els.connectionBadge.textContent=on?'online':'offline';}
window.addEventListener('online',online);window.addEventListener('offline',online);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('load',()=>{online();reset();});